
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "static/uploads"
public_folder: "/uploads"

collection:
  -name: 'projects'
   label: 'Projects'
   folder: 'projects'
   create: true
   fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'featuredImage', widget: 'image' }
      - { label: 'Poster Image', name: 'posterImage', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Release', name: 'release', widget: 'number' }
      - { label: 'Genre', name: 'genre', widget: 'string'}
      - { label: 'Tags', name: 'tags', widget: 'list'}
      - { label: 'Link', name: 'link', widget: 'string'}
